version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ubuntu